<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>5467fc50-b714-4b0c-b71b-f8fded833c2d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Sorry, we don't have enough information to provide a response." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
